---
- hosts: "{{ groups['irc']|first }}"
  connection: local
  gather_facts: no
  tasks:
    - include_role:
        name: ovh
      delegate_to: localhost
- hosts: irc
  remote_user: root
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  roles:
    - acme.sh
    - thelounge
  tasks:
    - name: Copy ssh keys
      authorized_key:
        user: root
        state: present
        key: "{{ public_key }}"
